#!/bin/sh

set -e

INSTALL_PACKAGES=""
YADM_PROJECT_DIR="$HOME/.local/share/yadm-project"

cd "$HOME"

main(){
  echo -- setup yadm
  setup_yadm
  echo yadm: $yadm

  echo "Updating the yadm repo origin URL"
  $yadm remote set-url origin "git@github.com:calmsea/dotfiles.git"

  CLASSES=$($yadm config --get-all local.class)

  #
  # check
  #
  echo -- check
  echo local.class: ${CLASSES}
  check
}

#
# setup yadm
#
setup_yadm(){
  pushd $HOME/.local/share/yadm/repo.git
  git submodule update --init --recursive
  popd

  if [ -f "${YADM_PROJECT_DIR}/yadm" ]; then
    yadm="${YADM_PROJECT_DIR}/yadm"
  else
    yadm=$(which yadm)
  fi
  $yadm version
  rm -f ${HOME}/.local/bin/yadm && ln -s $yadm ${HOME}/.local/bin/yadm
}

#
#
#
check(){
  commands="zsh dash vi vim python python3 git awk emacs tmux"
  available=""
  unavailable=""
  for cmd in $commands; do
    if which "$cmd" >& /dev/null; then
      available="$available$cmd "
    else
      unavailable="$unavailable$cmd "
    fi
  done
  echo "commands(available)   : "$available
  echo "commands(unavailable) : "$unavailable
}

#
# run main
#
main

# EOF
