#!/usr/bin/bash
#
# login        : profile .> sh/profile .> bashrc .> sh/bashrc
# interfactive : bashrc .> sh/bashrc
# scripts      : 
#

test -d "$XDG_STATE_HOME/bash" || mkdir -p "$XDG_STATE_HOME/bash"
test -d "$XDG_CACHE_HOME/bash" || mkdir -p "$XDG_CACHE_HOME/bash"
test -d "$XDG_DATA_HOME/bash"  || mkdir -p "$XDG_DATA_HOME/bash"

HISTFILE="$XDG_STATE_HOME/bash/history"

# completion
if [ -f "$XDG_DATA_HOME/yadm-project/completion/bash/yadm" ]; then
    . "$XDG_DATA_HOME/yadm-project/completion/bash/yadm"
fi

# EOF
