#!/bin/sh

: ${XDG_BIN_HOME:=$HOME/.local/bin}

if [ ! -d $XDG_BIN_HOME ]; then
    mkdir -p $XDG_BIN_HOME
fi
tmp=${PATH#"*${XDG_BIN_HOME}"}
if [ "$tmp" = "$PATH" ]; then
    PATH="${XDG_BIN_HOME}:$PATH"
fi
export PATH

export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
export AZURE_CONFIG_DIR="$XDG_DATA_HOME"/azure
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export SQLITE_HISTORY="$XDG_DATA_HOME"/sqlite_history

# EOF
