#
live_config_reload = true

[window]
padding = { x = 4, y = 2 }
opacity = 0.9
dynamic_padding = true
decorations = "Full"
startup_mode = "Maximized"

[font]
size = 11.25
normal = { family = "PlemolJP Console", style = "Regular" }

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }

[mouse]
bindings = [{ mouse = "Right", action = "Paste" }]
